name: Canary

on:
  push:
    paths-ignore:
      - "documentation/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  prepare-version:
    name: Prepare Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate canary version
        id: set-version
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          VERSION=$(grep '^version\s*=' Cargo.toml | head -n 1 | cut -d\" -f2)
          VERSION="${VERSION}-canary+${SHORT_SHA}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-cli:
    needs: [prepare-version]
    uses: ./.github/workflows/build-cli.yml
    with:
      version: ${{ needs.prepare-version.outputs.version }}

  install-script:
    name: Upload Install Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: install-scripts
          path: |
            download_cli.sh
            download_cli.ps1

  release:
    name: Release Canary
    runs-on: ubuntu-latest
    needs: [build-cli, install-script]
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            a8e-*.tar.bz2
            a8e-*.zip
            download_cli.sh
            download_cli.ps1

      - name: Release canary
        uses: ncipollo/release-action@v1
        with:
          tag: canary
          name: Canary
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            a8e-*.tar.bz2
            a8e-*.zip
            download_cli.sh
            download_cli.ps1
          allowUpdates: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
